### PR TITLE
JSON5 Support

### PR DESCRIPTION
**Pull request by Hayden-J-C**
Added Json5FileFormat

### CODE REVIEW

**Review by itzg — DISMISSED** [review]
Excellent, thanks!

**Comment by itzg** [comment]
Hmm, test failed. Looks like I don't have it grabbing the test report on failure, so only have the line number of the failed assertion.

**Comment by Hayden-J-C** [comment]
Huh, I ran gradlew clean build before opening the PR. I'll look into it

**Comment by itzg** [comment]
Oh, I wonder if it's a Windows vs Linux line ending thing. I'm away from my computer, so I can't check, there might be an ignore line endings variant of assert.

**Comment by Hayden-J-C** [comment]
Got a chance to look into it, I think it's the parser acts differently on windows vs linux. Windows inserts a new line character with '\r\n' while linux just uses '\n'. Gonna try updating the "expected-setInJson5.json5" file to use '\n' instead

**Review by itzg — APPROVED** [review]
...and it still passes on Windows 😀

**Comment by itzg** [comment]
Included in this image build https://github.com/itzg/docker-minecraft-server/actions/runs/4836679121

**Pull request merged**
